# -*- coding: utf-8 -*-
"""Paule_S-CSPC315_EA Greedy Algorithm - Activity Selection Problem

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: S-CSPC315
DUE DATE: Dec 7

ASSIGNMENT: Enabling Assessment Module 6 - Greedy Algorithm (30 points)

TOPIC: Data Structures and Algorithms (DSA) - Greedy Algorithms, Activity Selection Problem, Interval Scheduling
PROBLEM: Activity Selection Problem
Given activities with start and end times, select the maximum number of 
non-overlapping activities that can be completed by a single person.
IDENTIFICATION: Implementing the Activity Selection Problem using a Greedy Algorithm to select the maximum number of non-overlapping activities that can be performed by a single person or resource. The algorithm sorts activities by end time, then greedily selects activities that start after or when the previous selected activity ends.

Programming Language: Python 3

Tech Stack:
- Python Standard Library only
- Built-in functions: sorted() with lambda key
- List of dictionaries for data storage
- No external dependencies

GREEDY ALGORITHM STEPS:
1. Sort activities by finishing time (ascending)
2. Select the first activity from the sorted list
3. For each remaining activity in sorted order:
   - If activity's start time ≥ last selected activity's end time
   - Select this activity and update the last end time
4. Output the optimal sequence of activities

TIME COMPLEXITY: O(n log n) - dominated by sorting
SPACE COMPLEXITY: O(n) - for storing selected activities
"""

# ============================================================================
# ACTIVITY DATA
# ============================================================================
# Each activity has: name identifier, start time, end time
activities = [
    {"name": "a1", "start": 6, "end": 10},
    {"name": "a2", "start": 2, "end": 3},
    {"name": "a3", "start": 4, "end": 5},
    {"name": "a4", "start": 1, "end": 7},
    {"name": "a5", "start": 6, "end": 8},   # Added as per requirements
    {"name": "a6", "start": 9, "end": 10},
]

print("=" * 60)
print("ACTIVITY SELECTION PROBLEM - GREEDY ALGORITHM")
print("=" * 60)

# Display all activities before sorting
print("\nAll activities (unsorted):")
for act in activities:
    print(f"  {act['name']}: start={act['start']}, end={act['end']}")

# ============================================================================
# STEP 1: SORT ACTIVITIES BY FINISHING TIME
# ============================================================================
# Greedy choice: always select the activity with the earliest end time
sorted_activities = sorted(activities, key=lambda x: x["end"])

print("\nActivities sorted by end time:")
for act in sorted_activities:
    print(f"  {act['name']}: start={act['start']}, end={act['end']}")

# ============================================================================
# STEP 2-3: GREEDY SELECTION
# ============================================================================
# Select the first activity (earliest end time)
selected_activities = [sorted_activities[0]]
last_end_time = sorted_activities[0]["end"]

# Iterate through remaining activities
for activity in sorted_activities[1:]:
    # If current activity starts after or when last ends → can be selected
    if activity["start"] >= last_end_time:
        selected_activities.append(activity)
        last_end_time = activity["end"]  # Update for next comparison

# ============================================================================
# STEP 4: OUTPUT OPTIMAL SOLUTION
# ============================================================================
print("\n" + "=" * 60)
print("OPTIMAL SOLUTION (Maximum non-overlapping activities)")
print("=" * 60)

print(f"\nTotal activities selected: {len(selected_activities)}")
print("\nSelected activity sequence (in chronological order):")
for i, activity in enumerate(selected_activities, 1):
    print(f"  {i}. Activity {activity['name']} "
          f"(Start: {activity['start']}, End: {activity['end']})")

# ============================================================================
# VISUAL TIMELINE REPRESENTATION
# ============================================================================
print("\n" + "=" * 60)
print("TIMELINE VISUALIZATION")
print("=" * 60)
print("\nTime:  1  2  3  4  5  6  7  8  9  10")
print("       |  |  |  |  |  |  |  |  |  |")

for activity in sorted_activities:
    line = "  "
    for t in range(1, 11):
        if activity["start"] <= t <= activity["end"]:
            line += "█"
        else:
            line += " "
    print(f"{activity['name']}: {line}")

print("\nSelected activities (█):")
for activity in selected_activities:
    print(f"  {activity['name']}")
