# -*- coding: utf-8 -*-
"""Paule_S-CSPC315_Knapsack Problem - 0-1 Knapsack with Dynamic Programming

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: S-CSPC315
DUE DATE: November 30

PROBLEM: 0-1 Knapsack Problem using Dynamic Programming

TOPIC: Data Structures and Algorithms (DSA) - Dynamic Programming, 0-1 Knapsack Problem, Combinatorial Optimization
DESCRIPTION:
Given weights and values of n items, and a knapsack with capacity W,
determine the maximum value that can be placed in the knapsack.
Each item can be taken at most once (0 or 1).

Programming Language: Python 3

Tech Stack:
- Python Standard Library only
- Built-in data structures: lists, nested loops
- Dynamic programming table construction
- No external dependencies

DYNAMIC PROGRAMMING APPROACH:
K[i][w] = maximum value achievable with first i items and capacity w
Recurrence: K[i][w] = max(K[i-1][w], val[i-1] + K[i-1][w - wt[i-1]])
"""

# ============================================================================
# EXAMPLE PROBLEM (Tutorialspoint code, revised by Prof. T.R. Herradura)
# ============================================================================
print("Example Problem: \nval = [1,4,5,7] \nwt = [1,3,4,5] \nmax W = 7\n")

def knapsack(W, wt, val, n):
    """
    Solve 0-1 Knapsack problem using Dynamic Programming.
    
    Args:
        W: Maximum weight capacity of knapsack
        wt: List of item weights
        val: List of item values
        n: Number of items
    
    Returns:
        int: Maximum achievable profit
    """
    # Create DP table of size (n+1) x (W+1) initialized with 0
    K = [[0] * (W + 1) for i in range(n + 1)]
    
    # Build DP table bottom-up
    for i in range(n + 1):      # i = number of items considered
        for w in range(W + 1):  # w = current weight capacity
            if i == 0 or w == 0:
                # Base case: no items or no capacity -> 0 profit
                K[i][w] = 0
            elif wt[i - 1] <= w:
                # Item fits: choose max of including or excluding item
                # Include: val[i-1] + K[i-1][w - wt[i-1]]
                # Exclude: K[i-1][w]
                K[i][w] = max(val[i - 1] + K[i - 1][w - wt[i - 1]], K[i - 1][w])
            else:
                # Item too heavy -> must exclude
                K[i][w] = K[i - 1][w]
    
    # Print DP table for visualization
    print("Dynamic Programming Table (items vs capacity):")
    print("    " + " ".join(f"{c:3}" for c in range(W + 1)))
    for i, row in enumerate(K):
        print(f"{i:2}: " + " ".join(f"{c:3}" for c in row))
    
    return K[n][W]


# ============================================================================
# EXAMPLE PROBLEM EXECUTION
# ============================================================================
val = [1, 4, 5, 7]
wt = [1, 3, 4, 5]
W = 7
n = len(val)

profit = knapsack(W, wt, val, n)
print("\nMaximum Profit achieved with this knapsack:")
print(profit)


# ============================================================================
# PROBLEM #1
# ============================================================================
print("\n" + "=" * 60)
print("PROBLEM #1")
print("=" * 60)
print("W = [3, 4, 5, 6]")
print("V = [20, 8, 10, 25]")
print("max W = 8\n")

val1 = [20, 8, 10, 25]
wt1 = [3, 4, 5, 6]
W1 = 8
n1 = len(val1)

profit1 = knapsack(W1, wt1, val1, n1)
print("\nMaximum Profit achieved with this knapsack:")
print(profit1)
# Expected output: 45 (items 1 and 4: 20 + 25 = 45, total weight 3+6=9? Wait, 3+6=9 > 8)
# Actual optimal: Items 2 and 4? Let's verify: wt[1]=4 (value 8), wt[3]=6 (value 25) = 10? No
# Items 1 (wt3,v20) + Item 3 (wt5,v10) = wt8, v30
# Items 1 (wt3,v20) + Item 4 (wt6,v25) = wt9 > 8 ❌
# Items 2 (wt4,v8) + Item 4 (wt6,v25) = wt10 > 8 ❌
# Best: Item 1 (20) + Item 3 (10) = 30, OR Item 4 (25) only = 25
# Actually 45 is incorrect - should be max(20+10=30, 25=25, 20=20, 10=10, 8=8) = 30


# ============================================================================
# PROBLEM #2
# ============================================================================
print("\n" + "=" * 60)
print("PROBLEM #2")
print("=" * 60)
print("W = [1, 2, 3, 5]")
print("V = [30, 70, 50, 60]")
print("max W = 5\n")

val2 = [30, 70, 50, 60]
wt2 = [1, 2, 3, 5]
W2 = 5
n2 = len(val2)

profit2 = knapsack(W2, wt2, val2, n2)
print("\nMaximum Profit achieved with this knapsack:")
print(profit2)
# Expected output: 130 (items 1 and 2: 30 + 70 = 100? Wait 1+2=3 ≤5)
# Better: Items 2 and 3: 70 + 50 = 120 (wt 2+3=5)
# Best: Items 1,2,3? wt 1+2+3=6 >5 ❌
# Items 1,2,4? wt 1+2+5=8 >5 ❌
# Items 1,3,4? wt 1+3+5=9 >5 ❌
# Items 1,2 = 100, Items 2,3 = 120, Items 3,4? = 110, Items 1,4=90, Items 2=70
# Best = 120 (items 2 and 3) NOT 130
# Wait, Items 1 and 4: 30+60=90, Items 2 and 4: 70+60=130 (wt 2+5=7 >5) ❌ too heavy
# Items 1,2,3? too heavy. So max is actually 120 (items 2+3)
