# -*- coding: utf-8 -*-
"""Paule_CSPC315_MergeSort - Merge Sort Algorithm with Recursive Tracing

Automatically generated by Colab.

STUDENT: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSPC315

Topic: Data Structures and Algorithms (DSA) - Divide and Conquer, Merge Sort, Recursion

Programming Language: Python 3
DESCRIPTION:
Merge Sort implementation using Divide and Conquer design technique.
The program includes tracing output showing the splitting and merging
process at each recursion level.
Implementing the Merge Sort algorithm using the divide and conquer paradigm with recursive tracing to visualize the sorting process. The program sorts an 8-element array and outputs intermediate steps showing splitting and merging at each recursion level.

ALGORITHM COMPLEXITY:
- Time Complexity: O(n log n) in all cases (best, average, worst)
- Space Complexity: O(n) for temporary arrays
- Stable sort: Yes

Tech Stack:
- Python Standard Library only
- No external dependencies
- Built-in functions: len(), print(), list slicing
"""

def merge_sort_with_trace(arr, depth=0):
    """
    Recursive Merge Sort implementation with tracing output.
    
    Args:
        arr: List to be sorted (modified in-place)
        depth: Current recursion depth (for indentation formatting)
    
    Algorithm Steps:
    1. If array has 1 element → base case (return)
    2. Divide: Split array into left and right halves
    3. Conquer: Recursively sort both halves
    4. Combine: Merge sorted halves back together
    """
    # Setup indentation based on recursion depth for trace formatting
    indent = "  " * depth
    print(f"{indent}Splitting: {arr}")

    # Base case: array with 0 or 1 element is already sorted
    if len(arr) > 1:
        # DIVIDE: Find middle index and split array
        mid = len(arr) // 2
        left_half = arr[:mid]   # Left subarray
        right_half = arr[mid:]  # Right subarray

        # CONQUER: Recursively sort both halves
        merge_sort_with_trace(left_half, depth + 1)
        merge_sort_with_trace(right_half, depth + 1)

        # COMBINE: Merge the two sorted halves
        # Initialize pointers:
        # i → left_half index, j → right_half index, k → original array index
        i = j = k = 0

        # Compare elements from left and right halves and add smaller to original
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]  # Take from left half
                i += 1
            else:
                arr[k] = right_half[j]  # Take from right half
                j += 1
            k += 1

        # Add any remaining elements from left half
        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        # Add any remaining elements from right half
        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

        # Log the merged result for this level
        print(f"{indent}Merging:  {arr}")
    else:
        # Base case reached (single element or empty array)
        print(f"{indent}Base case: {arr}")

# ============================================================================
# MAIN EXECUTION
# ============================================================================
# Input array with n=8 elements as specified
arr = [8, 3, 2, 9, 7, 1, 5, 4]

print("=" * 50)
print("MERGE SORT TRACE")
print("=" * 50)
print(f"Original array: {arr}")
print()

# Execute merge sort with tracing
merge_sort_with_trace(arr)

print()
print("=" * 50)
print(f"Sorted array:   {arr}")
print("=" * 50)
